name: sushi_shop_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_custom_clippers: ^2.1.0
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.4.0
  syncfusion_flutter_core: ^22.1.37
  syncfusion_flutter_sliders: ^22.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DMSans-Regular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
